/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2023-04-12 03:15:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.order;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class orderGoodsForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/projectAA/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/AA/WEB-INF/lib/tiles-jsp-2.2.2.jar!/META-INF/tld/tiles-jsp.tld", Long.valueOf(1276606224000L));
    _jspx_dependants.put("/WEB-INF/lib/tiles-jsp-2.2.2.jar", Long.valueOf(1675821942165L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1675821940594L));
    _jspx_dependants.put("jar:file:/C:/projectAA/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/AA/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>상품 구매하기창</title>\r\n");
      out.write("<style>  \r\n");
      out.write("body {\r\n");
      out.write("font-family: Arial, sans-serif;\r\n");
      out.write("background-color: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("#orderHead {\r\n");
      out.write("       font-size: 24px;\r\n");
      out.write("    line-height: 1.4;\r\n");
      out.write("    margin-left: 215px;\r\n");
      out.write("    padding-top: 15px;\r\n");
      out.write("} \r\n");
      out.write(".goodsBuyPNG {\r\n");
      out.write("  display:inline-block;\r\n");
      out.write("    float:right;\r\n");
      out.write("        margin-right: 50px;\r\n");
      out.write("}  \r\n");
      out.write(".goodsBuyForm{     \r\n");
      out.write("   width: 1050;\r\n");
      out.write("    height: 1000px;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    margin-left: 20px;\r\n");
      out.write("}  \r\n");
      out.write(".goodsBuyForm1{ \r\n");
      out.write("       width: 680px;\r\n");
      out.write("    border: 1px solid grey;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    margin-top: 0px;\r\n");
      out.write("    margin-left: 20px;\r\n");
      out.write("}  \r\n");
      out.write(".orderCheck{\r\n");
      out.write("   margin:0;\r\n");
      out.write("   width:100%;\r\n");
      out.write("   border-collapse: collapse;\r\n");
      out.write("}\r\n");
      out.write(".orderCheck .goods_img{\r\n");
      out.write("margin:10px;\r\n");
      out.write("   width:80px;\r\n");
      out.write("   height:70px;\r\n");
      out.write("}\r\n");
      out.write(".orderCheck .table_center{\r\n");
      out.write("   text-align:center;\r\n");
      out.write("}\r\n");
      out.write(".orderCheck tr{\r\n");
      out.write("   margin-bottom:10px;\r\n");
      out.write("   line-height: 2.2;\r\n");
      out.write("}\r\n");
      out.write(".goodsBuyForm2{ \r\n");
      out.write("   width: 300px;\r\n");
      out.write("    height: 350px;\r\n");
      out.write("    border: 1px solid grey;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    margin-left: 10px;\r\n");
      out.write("    margin-right: 0;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("}    \r\n");
      out.write(".goodsBuyForm3{ \r\n");
      out.write("   width: 680px;\r\n");
      out.write("    height: 250px;\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("    line-height: 1.6;\r\n");
      out.write("    padding: auto;\r\n");
      out.write("    margin-left: 20px;\r\n");
      out.write("    flex-direction: row;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("  .goodsBuyForm3 th {\r\n");
      out.write("    width: 400px; \r\n");
      out.write("  }\r\n");
      out.write(".goodsBuyForm3 td {\r\n");
      out.write("   font-size:1.3em;\r\n");
      out.write("   margin-top:5px;\r\n");
      out.write("}\r\n");
      out.write(".goodsBuyForm4{\r\n");
      out.write("   width: 680px;\r\n");
      out.write("    height: 150px;\r\n");
      out.write("    border: 1px solid grey;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("    margin-left: 20px;\r\n");
      out.write("}\r\n");
      out.write(".goodsBuyForm5{\r\n");
      out.write("   width: 680px;\r\n");
      out.write("    height: 250px;\r\n");
      out.write("    border: 1px solid grey;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("    margin-left: 20px;\r\n");
      out.write("}\r\n");
      out.write(".upperArrow{\r\n");
      out.write("   width:20px;\r\n");
      out.write("   height:20px;\r\n");
      out.write("   transform: rotate(180deg);\r\n");
      out.write("}\r\n");
      out.write(".upperArrow:hover{\r\n");
      out.write("}\r\n");
      out.write(".lowerArrow{\r\n");
      out.write("   width:20px;\r\n");
      out.write("   height:20px;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write(".lowerArrow:hover{\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function modify_goods_qty(goods_num,index, updown){\r\n");
      out.write("   var length = document.getElementsByName('order_goods_option').length;\r\n");
      out.write("   var _order_goods_qty=0;\r\n");
      out.write("   var input = document.getElementsByName(\"order_goods_qty\")[index];\r\n");
      out.write("   var input_price = document.getElementsByName(\"final_resultPrice\")[index];\r\n");
      out.write("   var goods_option = document.getElementsByName(\"order_goods_option\")[index];\r\n");
      out.write("   \r\n");
      out.write("   var value = Number(input.value);\r\n");
      out.write("   if(length>1){ //카트에 제품이 한개인 경우와 여러개인 경우 나누어서 처리한다.\r\n");
      out.write("      if(updown == \"up\"){\r\n");
      out.write("         \r\n");
      out.write("      if(value < 10){\r\n");
      out.write("         value += 1;\r\n");
      out.write("      }\r\n");
      out.write("      }else if(value > 0){\r\n");
      out.write("         value -+ 1;\r\n");
      out.write("      }\r\n");
      out.write("   }else if(updown == \"up\"){\r\n");
      out.write("         \r\n");
      out.write("      if(value < 10){\r\n");
      out.write("         value += 1;\r\n");
      out.write("      }\r\n");
      out.write("      }else if(value > 0){\r\n");
      out.write("         value -= 1;\r\n");
      out.write("      }\r\n");
      out.write("   \r\n");
      out.write("   $.ajax({\r\n");
      out.write("	   type: \"POST\",\r\n");
      out.write("	   url: \"modifyOrderOption.do\", // 서버측 코드\r\n");
      out.write("	   data: { goods_option: goods_option.value, goods_num: goods_num },\r\n");
      out.write("	   success: function (data) {\r\n");
      out.write("	     // 서버에서 계산된 가격을 받아와서 가격을 갱신\r\n");
      out.write("	     var price = data * value;\r\n");
      out.write("		 input_price.value = price;\r\n");
      out.write("	     document.getElementById('final_resultPrice_'+ index).textContent = price;\r\n");
      out.write("	     var totalPrice = 0;\r\n");
      out.write("	      $('span[id^=\"final_resultPrice_\"]').each(function () {\r\n");
      out.write("	        totalPrice += Number($(this).text());\r\n");
      out.write("	      });\r\n");
      out.write("	      $('#total_resultPrice').text(totalPrice);\r\n");
      out.write("	   // 최종 결제액 계산 및 갱신\r\n");
      out.write("	      var use_point = document.getElementsByName(\"use_point\")[0].value;\r\n");
      out.write("	      var total_price = document.getElementById(\"total_resultPrice\").textContent;\r\n");
      out.write("	      var final_price = Number(total_price) - Number(use_point);\r\n");
      out.write("	      document.getElementById(\"total_finalResultPrice\").textContent = final_price;\r\n");
      out.write("	      document.getElementById(\"total_finalPrice\").value = final_price;\r\n");
      out.write("	    }\r\n");
      out.write("	 });\r\n");
      out.write("   \r\n");
      out.write("   input.value = value;\r\n");
      out.write("     document.getElementById('qty_' + index).textContent = value;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function modify_goods_option(goods_num, index, updown) {\r\n");
      out.write("     var length = document.getElementsByName('order_goods_option').length;\r\n");
      out.write("     var goods_option = \"standard\";\r\n");
      out.write("	 var qty = document.getElementsByName(\"order_goods_qty\")[index];\r\n");
      out.write("     var input = document.getElementsByName(\"order_goods_option\")[index];\r\n");
      out.write("	 var input_price = document.getElementsByName(\"final_resultPrice\")[index];\r\n");
      out.write("     if (length > 1) {\r\n");
      out.write("       if (input.value == \"standard\") {\r\n");
      out.write("         if (updown == \"up\") {\r\n");
      out.write("           goods_option = \"deluxe\";\r\n");
      out.write("         } else {\r\n");
      out.write("           goods_option = \"standard\";\r\n");
      out.write("         }\r\n");
      out.write("       } else if (input.value == \"deluxe\") {\r\n");
      out.write("         if (updown == \"up\") {\r\n");
      out.write("           goods_option = \"premium\";\r\n");
      out.write("         } else {\r\n");
      out.write("           goods_option = \"standard\";\r\n");
      out.write("         }\r\n");
      out.write("       } else if (input.value == \"premium\") {\r\n");
      out.write("         if (updown == \"up\") {\r\n");
      out.write("           goods_option = \"deluxe\";\r\n");
      out.write("         } else {\r\n");
      out.write("           goods_option = \"standard\";\r\n");
      out.write("         }\r\n");
      out.write("       }\r\n");
      out.write("     } else {\r\n");
      out.write("       if (input.value == \"standard\") {\r\n");
      out.write("         if (updown == \"up\") {\r\n");
      out.write("           goods_option = \"deluxe\";\r\n");
      out.write("         } else {\r\n");
      out.write("           goods_option = \"standard\";\r\n");
      out.write("         }\r\n");
      out.write("       } else if (input.value == \"deluxe\") {\r\n");
      out.write("         if (updown == \"up\") {\r\n");
      out.write("           goods_option = \"premium\";\r\n");
      out.write("         } else {\r\n");
      out.write("           goods_option = \"standard\";\r\n");
      out.write("         }\r\n");
      out.write("       } else if (input.value == \"premium\") {\r\n");
      out.write("         if (updown == \"up\") {\r\n");
      out.write("           goods_option = \"premium\";\r\n");
      out.write("         } else {\r\n");
      out.write("           goods_option = \"deluxe\";\r\n");
      out.write("         }\r\n");
      out.write("       }\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     input.value = goods_option;\r\n");
      out.write("     document.getElementById('option_' + index).textContent = input.value;\r\n");
      out.write("     \r\n");
      out.write("  // setter 호출\r\n");
      out.write("     $.ajax({\r\n");
      out.write("    	   type: \"POST\",\r\n");
      out.write("    	   url: \"modifyOrderOption.do\", // 서버측 코드\r\n");
      out.write("    	   data: { goods_option: goods_option, goods_num: goods_num },\r\n");
      out.write("    	   success: function (data) {\r\n");
      out.write("    	     // 서버에서 계산된 가격을 받아와서 가격을 갱신\r\n");
      out.write("    	     var price = data * qty.value;\r\n");
      out.write("    		 input_price.value = price;\r\n");
      out.write("    	     document.getElementById('final_resultPrice_'+ index).textContent = price;\r\n");
      out.write("    	     var totalPrice = 0;\r\n");
      out.write("    	      $('span[id^=\"final_resultPrice_\"]').each(function () {\r\n");
      out.write("    	        totalPrice += Number($(this).text());\r\n");
      out.write("    	      });\r\n");
      out.write("    	      $('#total_resultPrice').text(totalPrice);\r\n");
      out.write("    	   // 최종 결제액 계산 및 갱신\r\n");
      out.write("    	      var use_point = document.getElementsByName(\"use_point\")[0].value;\r\n");
      out.write("    	      var total_price = document.getElementById(\"total_resultPrice\").textContent;\r\n");
      out.write("    	      var final_price = Number(total_price) - Number(use_point);\r\n");
      out.write("    	      document.getElementById(\"total_finalResultPrice\").textContent = final_price;\r\n");
      out.write("    	      document.getElementById(\"total_finalPrice\").value = final_price;\r\n");
      out.write("    	    }\r\n");
      out.write("    	 });\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("var goods_num;\r\n");
      out.write("var goods_title;\r\n");
      out.write("var goods_fileName;\r\n");
      out.write("var order_goods_qty;\r\n");
      out.write("var total_order_goods_qty;\r\n");
      out.write("var orderer_name;\r\n");
      out.write("var orderer_tel; \r\n");
      out.write("var orderer_email; \r\n");
      out.write("\r\n");
      out.write("var pay_method; \r\n");
      out.write("var card_com_name; \r\n");
      out.write("var card_pay_month; \r\n");
      out.write("\r\n");
      out.write("function fn_show_order_detail() {\r\n");
      out.write("   goods_num = \"\";\r\n");
      out.write("   goods_title = \"\";\r\n");
      out.write("\r\n");
      out.write("   var frm = document.form_order;\r\n");
      out.write("   var goods_num = frm.goods_num;\r\n");
      out.write("   var goods_title = frm.goods_title;\r\n");
      out.write("   var goods_fileName = frm.goods_fileName;\r\n");
      out.write("   var order_goods_qty = document.getElementById(\"order_goods_qty\");\r\n");
      out.write("   var total_order_goods_qty = document\r\n");
      out.write("         .getElementById(\"total_order_goods_qty\");\r\n");
      out.write("   var total_sales_price = document\r\n");
      out.write("         .getElementById(\"total_sales_price\");\r\n");
      out.write("   var final_total_Price = document\r\n");
      out.write("         .getElementById(\"final_total_Price\");\r\n");
      out.write("   var orderer_name = document.getElementById(\"orderer_name\");\r\n");
      out.write("  \r\n");
      out.write("   if (goods_num.length < 2 || goods_num.length == null) {\r\n");
      out.write("      goods_num += goods_num.value;\r\n");
      out.write("   } else {\r\n");
      out.write("      for (var i = 0; i < goods_num.length; i++) {\r\n");
      out.write("         goods_num += goods_num[i].value + \"<br>\";\r\n");
      out.write("\r\n");
      out.write("      }\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("   if (goods_title.length < 2 || goods_title.length == null) {\r\n");
      out.write("      goods_title += goods_title.value;\r\n");
      out.write("   } else {\r\n");
      out.write("      for (var i = 0; i < goods_title.length; i++) {\r\n");
      out.write("         goods_title += goods_title[i].value + \"<br>\";\r\n");
      out.write("\r\n");
      out.write("      }\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   total_order_goods_price = final_total_Price.value;\r\n");
      out.write("   total_order_goods_qty = total_order_goods_qty.value;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   var r_pay_method = frm.pay_method;\r\n");
      out.write("\r\n");
      out.write("   for (var i = 0; i < r_pay_method.length; i++) {\r\n");
      out.write("      if (r_pay_method[i].checked == true) {\r\n");
      out.write("         pay_method = r_pay_method[i].value\r\n");
      out.write("         if (pay_method == \"신용카드\") {\r\n");
      out.write("            var card_com_name = document\r\n");
      out.write("                  .getElementById(\"card_com_name\");\r\n");
      out.write("            var card_pay_month = document\r\n");
      out.write("                  .getElementById(\"card_pay_month\");\r\n");
      out.write("            card_com_name = card_com_name.value;\r\n");
      out.write("            card_pay_month = card_pay_month.value;\r\n");
      out.write("            pay_method += \"<Br>\" + \"카드사:\" + card_com_name + \"<br>\"\r\n");
      out.write("                  + \"할부개월수:\" + card_pay_month;\r\n");
      out.write("            pay_orderer_tel = \"해당없음\";\r\n");
      out.write("\r\n");
      out.write("         } else if (pay_method == \"휴대폰결제\") {\r\n");
      out.write("            var pay_order_tel= document\r\n");
      out.write("                  .getElementById(\"pay_order_tel\");   \r\n");
      out.write("            pay_method += \"<Br>\" + \"결제휴대폰번호:\" + pay_orderer_hp_num;\r\n");
      out.write("            card_com_name = \"해당없음\";\r\n");
      out.write("            card_pay_month = \"해당없음\";\r\n");
      out.write("         } //end if\r\n");
      out.write("         break;\r\n");
      out.write("      }// end for\r\n");
      out.write("   }\r\n");
      out.write("}\r\n");
      out.write("function fn_process_pay_order() {\r\n");
      out.write("	   alert(\"최종 결제하기\");\r\n");
      out.write("	   \r\n");
      out.write("	   // form 요소 생성\r\n");
      out.write("	   var formObj = document.createElement(\"form\");\r\n");
      out.write("	   \r\n");
      out.write("	   // input 요소 생성\r\n");
      out.write("	   var orderer_name = document.createElement(\"input\");\r\n");
      out.write("	   var orderer_id = document.createElement(\"input\"); // 변수명 수정\r\n");
      out.write("	   var orderer_tel = document.createElement(\"input\");\r\n");
      out.write("	   var orderer_email = document.createElement(\"input\");\r\n");
      out.write("	   var pay_method = document.createElement(\"input\");\r\n");
      out.write("	   var card_com_name = document.createElement(\"input\");\r\n");
      out.write("	   var card_pay_month = document.createElement(\"input\");\r\n");
      out.write("	   var order_price = document.createElement(\"input\");\r\n");
      out.write("	   var order_goods_qty = document.createElement(\"input\");\r\n");
      out.write("	   var order_goods_option = document.createElement(\"input\");\r\n");
      out.write("	   \r\n");
      out.write("	   pay_method1 = document.getElementsByName(\"pay_method\");\r\n");
      out.write("	   var selected_pay_method;\r\n");
      out.write("	   for (var i = 0; i < pay_method1.length; i++) {\r\n");
      out.write("		   if (pay_method1[i].checked) {\r\n");
      out.write("		     selected_pay_method = pay_method1[i].value;\r\n");
      out.write("		     break;\r\n");
      out.write("		   }\r\n");
      out.write("		 }\r\n");
      out.write("	   \r\n");
      out.write("	   \r\n");
      out.write("	   // input 요소의 name 속성값 설정\r\n");
      out.write("	   orderer_name.name = \"orderer_name\";\r\n");
      out.write("	   orderer_id.name = \"orderer_id\"; // 변수명 수정\r\n");
      out.write("	   orderer_tel.name = \"orderer_tel\";\r\n");
      out.write("	   orderer_email.name = \"orderer_email\";\r\n");
      out.write("	   pay_method.name = \"pay_method\";\r\n");
      out.write("	   card_com_name.name = \"card_com_name\";\r\n");
      out.write("	   card_pay_month.name = \"card_pay_month\";\r\n");
      out.write("	   order_price.name = \"order_price\";\r\n");
      out.write("	   order_goods_qty.name = \"order_goods_qty\";\r\n");
      out.write("	   order_goods_option.name=\"order_goods_option\";\r\n");
      out.write("	 \r\n");
      out.write("	   // input 요소의 value 속성값 설정\r\n");
      out.write("	   orderer_name.value = document.getElementsByName(\"ordererName\").value; // 값을 할당할 변수명을 지정해주어야 합니다.\r\n");
      out.write("	   orderer_id.value = document.getElementsByName(\"ordererId\").value; // 변수값을 할당할 변수명을 지정해주어야 합니다.\r\n");
      out.write("	   orderer_tel.value = document.getElementsByName(\"ordererTel\").value;\r\n");
      out.write("	   orderer_email.value = document.getElementsByName(\"ordererEmail\").value;\r\n");
      out.write("	   pay_method.value = selected_pay_method;\r\n");
      out.write("	   card_com_name.value = document.getElementById(\"card_com_name\").value;\r\n");
      out.write("	   card_pay_month.value = document.getElementById(\"card_pay_month\").value;\r\n");
      out.write("	   order_price.value = document.getElementById(\"total_finalPrice\").value;\r\n");
      out.write("	   order_goods_qty.value = document.getElementsByName(\"order_goods_qty\")[0].value;\r\n");
      out.write("	   order_goods_option.value = document.getElementsByName(\"order_goods_option\")[0].value;\r\n");
      out.write("\r\n");
      out.write("	   \r\n");
      out.write("	   // 생성한 input 요소를 form 요소에 추가\r\n");
      out.write("	   formObj.appendChild(orderer_name);\r\n");
      out.write("	   formObj.appendChild(orderer_id);\r\n");
      out.write("	   formObj.appendChild(orderer_tel);\r\n");
      out.write("	   formObj.appendChild(orderer_email);\r\n");
      out.write("	   formObj.appendChild(pay_method);\r\n");
      out.write("	   formObj.appendChild(card_com_name);\r\n");
      out.write("	   formObj.appendChild(card_pay_month);\r\n");
      out.write("	   formObj.appendChild(order_price);\r\n");
      out.write("	   formObj.appendChild(order_goods_qty);\r\n");
      out.write("	   formObj.appendChild(order_goods_option);\r\n");
      out.write("\r\n");
      out.write("	   \r\n");
      out.write("	   // form 요소를 body에 추가하고, method와 action 속성값 설정 후 submit\r\n");
      out.write("	   document.body.appendChild(formObj);\r\n");
      out.write("	   formObj.method = \"post\";\r\n");
      out.write("	   formObj.action = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/payToOrderGoods.do\";\r\n");
      out.write("	   formObj.submit();\r\n");
      out.write("	   \r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head> \r\n");
      out.write("<body>  \r\n");
      out.write("   <img class=\"goodsBuyPNG\" alt=\"결제창\"  src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/goodsHead.png\">\r\n");
      out.write("   <h3 id=\"orderHead\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;상품 구매하기</h3> \r\n");
      out.write("   \r\n");
      out.write("   <form class=\"goodsBuyForm\">\r\n");
      out.write("   \r\n");
      out.write("   <div class=\"goodsBuyForm1\">\r\n");
      out.write("   <table class=\"orderCheck\">\r\n");
      out.write("      <tr style=\"border-bottom:2px solid lightgray;\">\r\n");
      out.write("         <td colspan=\"2\"><h2 style=\"font-size:20px; margin-left:20px;\">주문내역</h2></td>\r\n");
      out.write("         <td>상품 옵션</td>\r\n");
      out.write("         <td>주문 수량</td>\r\n");
      out.write("         <td>결제 금액</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <form name=\"frm_order_all_cart\">\r\n");
      out.write("      ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("   </table>\r\n");
      out.write("   </div>\r\n");
      out.write("   <table class=\"goodsBuyForm2\">  \r\n");
      out.write("      <tr style=\"border-bottom:2px solid lightgray;\">\r\n");
      out.write("         <td>서비스 금액</td>\r\n");
      out.write("         <td><span id=\"total_resultPrice\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>원</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr style=\"border-bottom:2px solid lightgray;\">\r\n");
      out.write("         <td>포인트 할인</td>\r\n");
      out.write("         <td><input type=\"hidden\" name=\"use_point\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${use_point}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr style=\"border-bottom:2px solid lightgray;\">\r\n");
      out.write("         <td>최종 결제액</td>\r\n");
      out.write("         <td><input type=\"hidden\" id=\"total_finalPrice\" name=\"total_finalResultPrice\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalPrice - use_point}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /><span id=\"total_finalResultPrice\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalPrice - use_point}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>원</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("   	<tr>\r\n");
      out.write("   	<td><button>취소하기</button>\r\n");
      out.write("   	<button>구매하기</button></td>\r\n");
      out.write("   	</tr>\r\n");
      out.write("   \r\n");
      out.write("   </table>\r\n");
      out.write("   <table class=\"goodsBuyForm3\" border=\"1\" > \r\n");
      out.write("    <tr align =\"center\">  \r\n");
      out.write("   <th colspan = \"2\" style=\"font-size:2em;\">구매자 정보</th>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("    <tr align = \"center\" >\r\n");
      out.write("   <td>회원 이름</td>\r\n");
      out.write("   <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderer.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<input type=\"hidden\" name=\"ordererName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderer.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("    <tr align = \"center\" >\r\n");
      out.write("   <td>회원 ID</td>\r\n");
      out.write("   <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderer.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<input type=\"hidden\" name=\"ordererId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderer.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("    <tr align = \"center\" >\r\n");
      out.write("   <td>회원 휴대폰 번호</td>\r\n");
      out.write("   <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderer.tel }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<input type=\"hidden\" name=\"ordererTel\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderer.tel}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("    <tr align = \"center\" >\r\n");
      out.write("   <td>회원 주소</td>\r\n");
      out.write("   <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderer.roadAdd }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderer.jibunAdd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderer.namujiAdd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<input type=\"hidden\" name=\"ordererRoadAdd\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderer.roadAdd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /><input type=\"hidden\" name=\"ordererJibunAdd\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderer.jibunAdd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /><input type=\"hidden\" name=\"ordererNamujiAdd\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderer.namujiAdd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("    <tr align = \"center\" >\r\n");
      out.write("   <td>회원 e-mail</td>\r\n");
      out.write("   <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderer.email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<input type=\"hidden\" name=\"ordererEmail\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderer.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("   <table class=\"goodsBuyForm4\">  <!-- 포인트 사용 -->\r\n");
      out.write("   	<tr>\r\n");
      out.write("   		<td>포인트 사용</td>\r\n");
      out.write("   	</tr>\r\n");
      out.write("   	<tr>\r\n");
      out.write("   		<td>현재 포인트</td>\r\n");
      out.write("   		<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderer.point}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("원</td>\r\n");
      out.write("   	</tr>\r\n");
      out.write("   	<tr>\r\n");
      out.write("  <td><input type=\"text\" id=\"point-input\" /></td>\r\n");
      out.write("  <td><button id=\"apply-btn\">적용</button></td>\r\n");
      out.write("</tr>\r\n");
      out.write("   </table>\r\n");
      out.write("   <table class=\"goodsBuyForm5\">  <!-- 결제 방법 -->\r\n");
      out.write("   <tbody>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td><input type=\"radio\" name=\"pay_method\"\r\n");
      out.write("                     value=\"신용카드\" onClick=\"fn_pay_card()\" checked>신용카드\r\n");
      out.write("                     &nbsp;&nbsp;&nbsp; <input type=\"radio\" id=\"pay_method\"\r\n");
      out.write("                     name=\"pay_method\" value=\"제휴 신용카드\">제휴 신용카드\r\n");
      out.write("                     &nbsp;&nbsp;&nbsp; <input type=\"radio\" id=\"pay_method\"\r\n");
      out.write("                     name=\"pay_method\" value=\"실시간 계좌이체\">실시간 계좌이체\r\n");
      out.write("                     &nbsp;&nbsp;&nbsp; <input type=\"radio\" id=\"pay_method\"\r\n");
      out.write("                     name=\"pay_method\" value=\"무통장 입금\">무통장 입금\r\n");
      out.write("                     &nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td><input type=\"radio\" name=\"pay_method\"\r\n");
      out.write("                     value=\"휴대폰결제\" onClick=\"fn_pay_phone()\">휴대폰 결제\r\n");
      out.write("                     &nbsp;&nbsp;&nbsp; <input type=\"radio\" id=\"pay_method\"\r\n");
      out.write("                     name=\"pay_method\" value=\"카카오페이(간편결제)\">카카오페이(간편결제)\r\n");
      out.write("                     &nbsp;&nbsp;&nbsp; <input type=\"radio\" id=\"pay_method\"\r\n");
      out.write("                     name=\"pay_method\" value=\"페이나우(간편결제)\">페이나우(간편결제)\r\n");
      out.write("                     &nbsp;&nbsp;&nbsp; <input type=\"radio\" id=\"pay_method\"\r\n");
      out.write("                     name=\"pay_method\" value=\"페이코(간편결제)\">페이코(간편결제)\r\n");
      out.write("                     &nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td><input type=\"radio\" name=\"pay_method\"\r\n");
      out.write("                     value=\"직접입금\">직접입금&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr id=\"tr_pay_card\">\r\n");
      out.write("                  <td><strong>카드 선택<strong>:&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                           <select id=\"card_com_name\" name=\"card_com_name\">\r\n");
      out.write("                              <option value=\"삼성\" selected>삼성</option>\r\n");
      out.write("                              <option value=\"하나SK\">하나SK</option>\r\n");
      out.write("                              <option value=\"현대\">현대</option>\r\n");
      out.write("                              <option value=\"KB\">KB</option>\r\n");
      out.write("                              <option value=\"신한\">신한</option>\r\n");
      out.write("                              <option value=\"롯데\">롯데</option>\r\n");
      out.write("                              <option value=\"BC\">BC</option>\r\n");
      out.write("                              <option value=\"시티\">시티</option>\r\n");
      out.write("                              <option value=\"NH농협\">NH농협</option>\r\n");
      out.write("                        </select> <br>\r\n");
      out.write("                        <Br> <strong>할부 기간:<strong>\r\n");
      out.write("                                 &nbsp;&nbsp;&nbsp; <select id=\"card_pay_month\"\r\n");
      out.write("                                 name=\"card_pay_month\">\r\n");
      out.write("                                    <option value=\"일시불\" selected>일시불</option>\r\n");
      out.write("                                    <option value=\"2개월\">2개월</option>\r\n");
      out.write("                                    <option value=\"3개월\">3개월</option>\r\n");
      out.write("                                    <option value=\"4개월\">4개월</option>\r\n");
      out.write("                                    <option value=\"5개월\">5개월</option>\r\n");
      out.write("                                    <option value=\"6개월\">6개월</option>\r\n");
      out.write("                              </select></td>\r\n");
      out.write("               </tr>\r\n");
      out.write("            </tbody>\r\n");
      out.write("   <tr>\r\n");
      out.write("                     <td colspan=2 align=center><input\r\n");
      out.write("                           name=\"btn_process_pay_order\" type=\"button\"\r\n");
      out.write("                           onClick=\"fn_process_pay_order()\" value=\"최종결제하기\"></td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("   </table>\r\n");
      out.write("   </form>\r\n");
      out.write("</body>\r\n");
      out.write("</html> ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/order/orderGoodsForm.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/order/orderGoodsForm.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/order/orderGoodsForm.jsp(6,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/order/orderGoodsForm.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("myOrderGoods");
      // /WEB-INF/views/order/orderGoodsForm.jsp(7,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/order/orderGoodsForm.jsp(7,0) '${orderMap.myOrderGoods}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${orderMap.myOrderGoods}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /WEB-INF/views/order/orderGoodsForm.jsp(8,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("orderGoodsCompany");
      // /WEB-INF/views/order/orderGoodsForm.jsp(8,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/order/orderGoodsForm.jsp(8,0) '${orderMap.orderGoodsCompany}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${orderMap.orderGoodsCompany}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f3 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f3_reused = false;
    try {
      _jspx_th_c_005fset_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f3.setParent(null);
      // /WEB-INF/views/order/orderGoodsForm.jsp(9,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setVar("orderList");
      // /WEB-INF/views/order/orderGoodsForm.jsp(9,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/order/orderGoodsForm.jsp(9,0) '${orderMap.orderList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${orderMap.orderList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f3 = _jspx_th_c_005fset_005f3.doStartTag();
      if (_jspx_th_c_005fset_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
      _jspx_th_c_005fset_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/order/orderGoodsForm.jsp(431,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("item");
      // /WEB-INF/views/order/orderGoodsForm.jsp(431,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/order/orderGoodsForm.jsp(431,6) '${orderList }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${orderList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/order/orderGoodsForm.jsp(431,6) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("cnt");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("      ");
            if (_jspx_meth_c_005fset_005f4(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("    ");
            if (_jspx_meth_c_005fset_005f5(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("      <tr>\r\n");
            out.write("         <td><a href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/goods/goodsDetail.do?goods_num=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.goods_num }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                     <img width=\"75\" alt=\"\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/thumbnails.do?goods_num=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.goods_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&fileName=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.goods_fileName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"  />\r\n");
            out.write("                  </a></td>\r\n");
            out.write("         <td><a href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/goods/goodsDetail.do?goods_num=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.goods_num }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods_title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a> <br><a href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/goods/goodsDetail.do?goods_num=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.goods_num }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"><h2>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h2></a> </td>\r\n");
            out.write("         <td class=\"table_center\"><img class=\"upperArrow\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/image/arrow1.png\" onclick=\"javascript:modify_goods_option('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.goods_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cnt.count-1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("','up');\"><br><input name=\"order_goods_option\" type=\"hidden\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.order_goods_option}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" /><span id=\"option_");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cnt.count-1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.order_goods_option }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span><br><img class=\"lowerArrow\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/image/arrow1.png\" onclick=\"javascript:modify_goods_option('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.goods_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cnt.count-1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("','down');\">\r\n");
            out.write("         </td>\r\n");
            out.write("         <td class=\"table_center\"><img class=\"upperArrow\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/image/arrow1.png\" onclick=\"javascript:modify_goods_qty('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.goods_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cnt.count-1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("','up');\"><br><input name=\"order_goods_qty\" type=\"hidden\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.order_goods_qty}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" /><span id=\"qty_");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cnt.count-1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.order_goods_qty}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span><br><img class=\"lowerArrow\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/image/arrow1.png\" onclick=\"javascript:modify_goods_qty('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.goods_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cnt.count-1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("','down');\">\r\n");
            out.write("         </td>\r\n");
            out.write("         <td class=\"table_center\"> <input name=\"final_resultPrice\" type=\"hidden\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.final_resultPrice * item.order_goods_qty}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" /><span id=\"final_resultPrice_");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cnt.count-1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.final_resultPrice * item.order_goods_qty}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" </span>원</td>\r\n");
            out.write("      </tr>\r\n");
            out.write("      ");
            if (_jspx_meth_c_005fset_005f6(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("      ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f4 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f4_reused = false;
    try {
      _jspx_th_c_005fset_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/order/orderGoodsForm.jsp(432,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f4.setVar("company_name");
      // /WEB-INF/views/order/orderGoodsForm.jsp(432,6) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f4.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/order/orderGoodsForm.jsp(432,6) '${orderGoodsCompany[cnt.count-1].company_name}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${orderGoodsCompany[cnt.count-1].company_name}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f4 = _jspx_th_c_005fset_005f4.doStartTag();
      if (_jspx_th_c_005fset_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f4);
      _jspx_th_c_005fset_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f5 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f5_reused = false;
    try {
      _jspx_th_c_005fset_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/order/orderGoodsForm.jsp(433,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f5.setVar("goods_title");
      // /WEB-INF/views/order/orderGoodsForm.jsp(433,4) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f5.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/order/orderGoodsForm.jsp(433,4) '${myOrderGoods[cnt.count-1].goods_title}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${myOrderGoods[cnt.count-1].goods_title}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f5 = _jspx_th_c_005fset_005f5.doStartTag();
      if (_jspx_th_c_005fset_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f5);
      _jspx_th_c_005fset_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f6 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f6_reused = false;
    try {
      _jspx_th_c_005fset_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/order/orderGoodsForm.jsp(445,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f6.setVar("totalPrice");
      // /WEB-INF/views/order/orderGoodsForm.jsp(445,6) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f6.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/order/orderGoodsForm.jsp(445,6) '${totalPrice += item.final_resultPrice * item.order_goods_qty}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${totalPrice += item.final_resultPrice * item.order_goods_qty}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f6 = _jspx_th_c_005fset_005f6.doStartTag();
      if (_jspx_th_c_005fset_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f6);
      _jspx_th_c_005fset_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f6_reused);
    }
    return false;
  }
}
