/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2023-04-11 00:06:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class comDetailInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/projectAA/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/AA/WEB-INF/lib/tiles-jsp-2.2.2.jar!/META-INF/tld/tiles-jsp.tld", Long.valueOf(1276606224000L));
    _jspx_dependants.put("/WEB-INF/lib/tiles-jsp-2.2.2.jar", Long.valueOf(1675821942165L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1675821940594L));
    _jspx_dependants.put("jar:file:/C:/projectAA/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/AA/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>  \r\n");
      out.write("body {\r\n");
      out.write("font-family: Arial, sans-serif;\r\n");
      out.write("background-color: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("/* Style for heading elements */\r\n");
      out.write("h1, h2, h3 {\r\n");
      out.write("font-weight: bold;\r\n");
      out.write("margin-top: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("font-size: 36px;\r\n");
      out.write("line-height: 1.2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2 {\r\n");
      out.write("font-size: 30px;\r\n");
      out.write("line-height: 1.3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h3 {\r\n");
      out.write("font-size: 24px; \r\n");
      out.write("line-height: 1.4;\r\n");
      out.write("}\r\n");
      out.write(".memInfo{    \r\n");
      out.write("   width: 850px; \r\n");
      out.write("   margin-left:330px;\r\n");
      out.write("    text-align: left;   \r\n");
      out.write("}\r\n");
      out.write(".memInfo .dot_line .fixed_join {\r\n");
      out.write("   width: 100px; \r\n");
      out.write("   text-align:center;\r\n");
      out.write("   font-weight:bold;\r\n");
      out.write("}   \r\n");
      out.write(".memInfo .dot_line fixed_join2 {   \r\n");
      out.write("   width:50px;    \r\n");
      out.write("}  \r\n");
      out.write(".memInfo .dot_line input[type=text],input[type=tel],input[type=email],input[type=password]{\r\n");
      out.write("   width:180px;\r\n");
      out.write("   height:30px;\r\n");
      out.write("   border-radius: 5px;\r\n");
      out.write("   margin : 7px 0px;\r\n");
      out.write("   padding-left:10px;\r\n");
      out.write("}\r\n");
      out.write(".memInfo input[type=button] {\r\n");
      out.write("   width: 100px; \r\n");
      out.write("   height:40px;\r\n");
      out.write("   border: 1px solid rgb(248, 248, 248);\r\n");
      out.write("   border-radius: 5px;\r\n");
      out.write("   background-color: rgb(245, 215, 0);\r\n");
      out.write("   color:#fff;   \r\n");
      out.write("}\r\n");
      out.write(".bottom3 {\r\n");
      out.write(" background-color: rgb(245, 215, 0);\r\n");
      out.write(" font-size:1.1em;\r\n");
      out.write(" font-weight: bold;\r\n");
      out.write("   width: 110px; height: 45px;\r\n");
      out.write("   border: none;\r\n");
      out.write("   color:White;\r\n");
      out.write("  position:relative; \r\n");
      out.write("  left:250px;\r\n");
      out.write("  top:10px;  \r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("}       \r\n");
      out.write(".bottom4 { \r\n");
      out.write("   background-color:#C4C4C4;\r\n");
      out.write(" font-size:1.1em;\r\n");
      out.write(" font-weight: bold;  \r\n");
      out.write("   width: 110px; height: 45px;\r\n");
      out.write("   border: none;\r\n");
      out.write("   color:White;\r\n");
      out.write("    position:relative;\r\n");
      out.write("  left:250px;\r\n");
      out.write("   top:10px;\r\n");
      out.write("   border-radius: 5px;\r\n");
      out.write("}   \r\n");
      out.write("</style>\r\n");

    session.removeAttribute("side_menu");

      out.write("\r\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write(" <script>\r\n");
      out.write(" function execDaumPostcode() {\r\n");
      out.write("       new daum.Postcode({\r\n");
      out.write("           oncomplete: function(data) {\r\n");
      out.write("               // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("               // 각 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("               // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("               var addr = ''; // 주소 변수\r\n");
      out.write("               var extraAddr = ''; // 참고항목 변수\r\n");
      out.write("\r\n");
      out.write("               //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\r\n");
      out.write("               if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\r\n");
      out.write("                   addr = data.roadAddress;\r\n");
      out.write("               } else { // 사용자가 지번 주소를 선택했을 경우(J)\r\n");
      out.write("                   addr = data.jibunAddress;\r\n");
      out.write("               }\r\n");
      out.write("\r\n");
      out.write("               // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.\r\n");
      out.write("               if(data.userSelectedType === 'R'){\r\n");
      out.write("                   // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("                   // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("                   if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\r\n");
      out.write("                       extraAddr += data.bname;\r\n");
      out.write("                   }\r\n");
      out.write("                   // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("                   if(data.buildingName !== '' && data.apartment === 'Y'){\r\n");
      out.write("                       extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("                   }\r\n");
      out.write("                   // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("                   if(extraAddr !== ''){\r\n");
      out.write("                       extraAddr = ' (' + extraAddr + ')';\r\n");
      out.write("                   }\r\n");
      out.write("                   // 조합된 참고항목을 해당 필드에 넣는다.\r\n");
      out.write("                   document.getElementById(\"company_jibunAdd\").value = extraAddr;\r\n");
      out.write("\r\n");
      out.write("               } else {\r\n");
      out.write("                   document.getElementById(\"company_jibunAdd\").value = '';\r\n");
      out.write("               }\r\n");
      out.write("\r\n");
      out.write("               // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("               document.getElementById('company_zipcode').value = data.zonecode;\r\n");
      out.write("               document.getElementById(\"company_roadAdd\").value = addr;\r\n");
      out.write("               // 커서를 상세주소 필드로 이동한다.\r\n");
      out.write("               document.getElementById(\"company_namujiAdd\").focus();\r\n");
      out.write("           }\r\n");
      out.write("       }).open();\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     function fn_modify_company_info(attribute){\r\n");
      out.write("       var value;\r\n");
      out.write("       // alert(company_id);\r\n");
      out.write("       // alert(\"mod_type:\"+mod_type);\r\n");
      out.write("          var frm_mod_company=document.frm_mod_company;\r\n");
      out.write("          if (attribute == 'pwd') {\r\n");
      out.write("              value = frm_mod_company.pwd.value;             \r\n");
      out.write("          }else if (attribute == 'company_name') {\r\n");
      out.write("              value = frm_mod_company.company_name.value;              	  \r\n");
      out.write("          } else if (attribute == 'nickname') {\r\n");
      out.write("               value = frm_mod_company.nickname.value;\r\n");
      out.write("          } else if(attribute == 'company_phone'){     \r\n");
      out.write("             var company_phone=frm_mod_company.company_phone;\r\n");
      out.write("             var smssts_yn=frm_mod_company.smssts_yn;\r\n");
      out.write("             \r\n");
      out.write("             value_company_phone=frm_mod_company.company_phone.value;\r\n");
      out.write("             value_smssts_yn=frm_mod_company.smssts_yn.checked;\r\n");
      out.write("             value=value_company_phone+\",\"+value_smssts_yn;\r\n");
      out.write("          }else if(attribute=='email'){\r\n");
      out.write("             var email=frm_mod_company.email;\r\n");
      out.write("             var emailsts_yn=frm_mod_company.emailsts_yn;\r\n");
      out.write("             \r\n");
      out.write("             value_email=frm_mod_company.email.value;\r\n");
      out.write("             value_emailsts_yn=frm_mod_company.emailsts_yn.checked;\r\n");
      out.write("             value=value_email+\",\"+value_emailsts_yn;\r\n");
      out.write("             //alert(value);\r\n");
      out.write("          }else if(attribute =='company_address'){\r\n");
      out.write("             var company_zipcode=frm_mod_company.company_zipcode;\r\n");
      out.write("             var company_roadAdd=frm_mod_company.company_roadAdd;\r\n");
      out.write("             var company_jibunAdd=frm_mod_company.company_jibunAdd;\r\n");
      out.write("             var company_namujiAdd=frm_mod_company.company_namujiAdd;\r\n");
      out.write("             \r\n");
      out.write("             value_company_zipcode=company_zipcode.value;\r\n");
      out.write("             value_company_roadAdd=company_roadAdd.value;\r\n");
      out.write("             value_company_jibunAdd=company_jibunAdd.value;\r\n");
      out.write("             value_company_namujiAdd=company_namujiAdd.value;\r\n");
      out.write("             value=value_company_zipcode+\",\"+value_company_roadAdd+\",\"+value_company_jibunAdd+\",\"+value_company_namujiAdd;\r\n");
      out.write("          }\r\n");
      out.write("          console.log(attribute);\r\n");
      out.write("        \r\n");
      out.write("          $.ajax({\r\n");
      out.write("             type : \"post\",\r\n");
      out.write("             async : false, //false인 경우 동기식으로 처리한다.\r\n");
      out.write("             url : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mypage/modifyComInfo.do\",\r\n");
      out.write("             data : {\r\n");
      out.write("                attribute:attribute,\r\n");
      out.write("                value:value,\r\n");
      out.write("             },\r\n");
      out.write("             success : function(data, textStatus) {\r\n");
      out.write("                if(data.trim()=='mod_success'){\r\n");
      out.write("                   alert(\"회사 정보를 수정했습니다.\");\r\n");
      out.write("                }else if(data.trim()=='failed'){\r\n");
      out.write("                   alert(\"다시 시도해 주세요.\");   \r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("             },\r\n");
      out.write("             error : function(data, textStatus) {\r\n");
      out.write("                alert(\"에러가 발생했습니다.\"+data);\r\n");
      out.write("             },\r\n");
      out.write("             complete : function(data, textStatus) {\r\n");
      out.write("                //alert(\"작업을완료 했습니다\");\r\n");
      out.write("                \r\n");
      out.write("             }\r\n");
      out.write("          }); //end ajax\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</head>  \r\n");
      out.write("<body>   \r\n");
      out.write("   <form method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mypage/modifyComInfo.do\" name=\"frm_mod_company\">\r\n");
      out.write("   <br> \r\n");
      out.write("   <h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;회사 정보 관리창</h3>\r\n");
      out.write("   <br><br> \r\n");
      out.write("      <table class=\"memInfo\" style=\"width:600px; height:500px;\">  \r\n");
      out.write("         <tr class=\"dot_line\">\r\n");
      out.write("               <td class=\"fixed_join\">아이디</td>\r\n");
      out.write("               <td class=\"fixed_join2\" style=\"width:100px;\">\r\n");
      out.write("                  <input name=\"id\" type=\"text\" size=\"20\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${companyInfo.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"width:220px;\" disabled/>\r\n");
      out.write("               </td> \r\n");
      out.write("            </tr>\r\n");
      out.write("              <tr class=\"dot_line\">  \r\n");
      out.write("               <td class=\"fixed_join\">비밀번호</td>\r\n");
      out.write("               <td> \r\n");
      out.write("                 <input name=\"pwd\" type=\"password\" size=\"20\" style=\"width:220px;\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${companyInfo.pwd }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type=\"button\" value=\"수정하기\" onClick=\"fn_modify_company_info('pwd')\" />\r\n");
      out.write("               </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("              <tr class=\"dot_line\">\r\n");
      out.write("               <td class=\"fixed_join\">회사명</td>\r\n");
      out.write("               <td>\r\n");
      out.write("                 <input name=\"company_name\" type=\"text\" size=\"20\" style=\"width:220px;\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${companyInfo.company_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"   />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type=\"button\" value=\"수정하기\" onClick=\"fn_modify_company_info('company_name')\" />\r\n");
      out.write("               </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("              <tr class=\"dot_line\">\r\n");
      out.write("               <td class=\"fixed_join\">대표 이름</td>\r\n");
      out.write("               <td>\r\n");
      out.write("                 <input name=\"capName\" type=\"text\" size=\"20\" style=\"width:220px;\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${companyInfo.capName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"  disabled />\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("              <tr class=\"dot_line\">\r\n");
      out.write("               <td class=\"fixed_join\">닉네임</td>\r\n");
      out.write("               <td>\r\n");
      out.write("                 <input name=\"nickname\" type=\"text\" size=\"20\" style=\"width:220px;\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${companyInfo.nickname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"   />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type=\"button\" value=\"수정하기\" onClick=\"fn_modify_company_info('nickname')\" />\r\n");
      out.write("               </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr class=\"dot_line\">\r\n");
      out.write("               <td class=\"fixed_join\">사업자등록번호</td>\r\n");
      out.write("               <td>\r\n");
      out.write("                 <input name=\"company_Number\" type=\"text\" size=\"20\" style=\"width:220px;\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${companyInfo.company_Number }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"  disabled />\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("               </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("               <tr class=\"dot_line\">\r\n");
      out.write("               <td class=\"fixed_join\">휴대폰 번호</td>\r\n");
      out.write("               <td>\r\n");
      out.write("                   <input type=\"text\" name=\"company_phone\" id=\"company_phone\" style=\"width:320px;\" size=10 value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${companyInfo.company_phone }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("                <Br><br> \r\n");
      out.write("               ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("               </td>\r\n");
      out.write("               <td style=\"width:120px;\">\r\n");
      out.write("                 <input type=\"button\" value=\"수정하기\" onClick=\"fn_modify_company_info('company_phone')\" />\r\n");
      out.write("               </td>\r\n");
      out.write("            </tr> \r\n");
      out.write("               <tr class=\"dot_line\">\r\n");
      out.write("               <td class=\"fixed_join\">이메일<br>(e-mail)</td>\r\n");
      out.write("               <td>\r\n");
      out.write("                   <input type=\"text\" name=\"email\" size=10 style=\"width:320px;\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${companyInfo.email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("                <Br><br> \r\n");
      out.write("               ");
      if (_jspx_meth_c_005fchoose_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("               </td>\r\n");
      out.write("               <td style=\"width:120px;\">\r\n");
      out.write("                 <input type=\"button\" value=\"수정하기\" onClick=\"fn_modify_company_info('email')\" />\r\n");
      out.write("               </td>\r\n");
      out.write("            </tr> \r\n");
      out.write("\r\n");
      out.write("            <tr class=\"dot_line\">\r\n");
      out.write("               <td class=\"fixed_join\">주소</td>\r\n");
      out.write("                 <td>\r\n");
      out.write("                 <p> \r\n");
      out.write("                    <input type=\"text\" id=\"company_zipcode\" name=\"company_zipcode\" size=\"15\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${companyInfo.company_zipcode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"  style=\"width:200px;\" placeholder=\"우편번호\">&nbsp;&nbsp;&nbsp;&nbsp;<input type=\"button\" value=\"우편번호검색\" onclick=\"execDaumPostcode()\"><br>\r\n");
      out.write("                  <b style=\"color:black;font-size:0.8em;\">도로명 주소</b><input type=\"text\" id=\"company_roadAdd\"  name=\"company_roadAdd\" size=\"50\" style=\"width:320px;\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${companyInfo.company_roadAdd }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><br><br>\r\n");
      out.write("                  <b style=\"color:black;font-size:0.8em;\">지번 주소</b><input type=\"text\" id=\"company_jibunAdd\" name=\"company_jibunAdd\" size=\"50\" style=\"width:320px;\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${companyInfo.company_jibunAdd }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><br><br>\r\n");
      out.write("                  <b style=\"color:black;font-size:0.8em;\">상세 주소</b><input type=\"text\"  id=\"company_namujiAdd\" name=\"company_namujiAdd\" size=\"50\" style=\"width:320px;\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${companyInfo.company_namujiAdd }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("                  </p>\r\n");
      out.write("               </td>  \r\n");
      out.write("               <td style=\"width:120px; height:300px;\">\r\n");
      out.write("                 <input type=\"button\" value=\"수정하기\" onClick=\"fn_modify_company_info('company_address')\" />\r\n");
      out.write("               </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("     </table>\r\n");
      out.write("           <div class=\"memInfo\"> \r\n");
      out.write("              <br><br>  \r\n");
      out.write("                 <input type=\"button\"  value=\"수정 완료\" id=\"check\" onClick=\"fn_check()\" class=\"bottom3\">\r\n");
      out.write("               <input type=\"hidden\" name=\"command\"  value=\"modify_com_info\" /> \r\n");
      out.write("                <input name=\"btn_cancel_company\" type=\"button\"  value=\"수정 취소\" class=\"bottom4\" style=\"background-color:#C4C4C4;\">\r\n");
      out.write("         </div>\r\n");
      out.write("        </form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/mypage/comDetailInfo.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/mypage/comDetailInfo.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/mypage/comDetailInfo.jsp(6,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" \r\n");
          out.write("                 ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                  ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/mypage/comDetailInfo.jsp(261,17) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${companyInfo.smssts_yn=='true' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                    <input type=\"checkbox\" name=\"smssts_yn\"  value=\"Y\" checked /> AA에서 발송하는 sms 소식을 수신합니다.\r\n");
          out.write("                  ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                    <input type=\"checkbox\" name=\"smssts_yn\"  value=\"N\"  /> AA에서 발송하는 sms 소식을 수신합니다.\r\n");
          out.write("                  ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent(null);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" \r\n");
          out.write("                 ");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                  ");
          if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /WEB-INF/views/mypage/comDetailInfo.jsp(279,17) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${companyInfo.emailsts_yn=='true' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                    <input type=\"checkbox\" name=\"emailsts_yn\"  value=\"Y\" checked /> AA에서 발송하는 e-mail을 수신합니다.\r\n");
          out.write("                  ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f1_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                    <input type=\"checkbox\" name=\"emailsts_yn\"  value=\"N\"  /> AA에서 발송하는 e-mail을 수신합니다.\r\n");
          out.write("                  ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      _jspx_th_c_005fotherwise_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f1_reused);
    }
    return false;
  }
}
